services:
  - type: web
    name: leaflens-ml-api
    env: python
    pythonVersion: 3.11.9
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT api:app
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT api:app
    autoDeploy: true
# heyyyyyy madarchodo